server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://150.158.98.98:3307/milu_search
    username: root
    password: 34ANP{d8z^f5
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://150.158.98.98:9200
    username: elastic
    password: zxc123..
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''